name: 안녕하세요. 정상현 입니다.
description: web publisher / front end developer
meta_description: "web publisher, front end developer  정상현의 개인 블로그 입니다."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://eyekorea.github.io/'
google_analytics: 'UA-64152133-X'

# Details for the RSS feed generator
url:            'http://eyekorea.github.io/'
author:         'eyekorea'